version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      VIRTUAL_HOST: ocr.qzhub.com
      VIRTUAL_PORT: 5000
networks:
  default:
    external:
      name: proxy_net
