version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      VIRTUAL_HOST: services.qzhub.com
      VIRTUAL_PORT: 8000
networks:
  default:
    external:
      name: proxy_net